### PR TITLE
Shift speed bar 1.5px right

### PR DESCRIPTION
**Pull request by 5h1zuy4**
Current:
    speed < MIN_V: 0
    speed > MAX_V: 182
    in between: 0 to 180 (rounded down from 0 to 180)
New:
    speed < MIN_V: 0
    speed > MAX_V: 182
    in between: 1 to 181 (rounded down from 1.5 to 181.5)

### CODE REVIEW

**Comment by hibiii** [comment]
At first I didn't get it, but I did some testing and it seems you are trying to fix the indicated speed being aligned with the colors on the bar, is that correct?

**Comment by 5h1zuy4** [comment]
correct

**Review by hibiii — COMMENTED** [review]
The leftmost pixel is always rendered as active with the water setting, even if the boat is at a complete standstill. It's also rendered with the blue ice setting when going full speed on packed ice.

**Comment by hibiii** [comment]
Fixed with 18d5d12caf93ad6268d5b1aafb35442c04ca974d

**Pull request closed without merging**
